version: '3.9'

services:
  database:
      image: postgres:16
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: hand_history
      volumes:
        - db_data:/var/lib/postgresql/data
        - ./Backend/app/sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  backend:
    build: ./Backend
    ports:
      - 8000:8000
    depends_on:
      - database
    
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - database
      - backend
  
  api_test:
    build: ./Backend
    volumes:
      - ./Backend:/app
    command: poetry run pytest .
    depends_on:
      - backend
      - database

  frontend_test:
    build: ./frontend_test
    depends_on:
      - backend
      - frontend
      - database
    ports:
      - 9323:9323

volumes:
  db_data: